[build]
  command = "yarn build"
  publish = "build"  # The directory where your production files are generated
  node_version = "16"  # Specify the node version (if needed)

[build.environment]
  CI = "false"  # Disable treating warnings as errors during build

